apiVersion: v1
kind: ConfigMap
metadata:
  name: snowflake-bot-config
data:
  AGENT_HOST: "0.0.0.0"
  AGENT_PORT: "8081"
  PYTHON_LOG_LEVEL: "INFO"
  USE_INMEMORY_SAVER: "true"
  MCP_ENABLED: "true"
  MCP_SERVER_NAME: "snowflake"
  MCP_SERVER_URL: "https://mcp-snowflake.apps.int.spoke.preprod.us-west-2.aws.paas.redhat.com/mcp"
  MCP_TRANSPORT_PROTOCOL: "streamable_http"
  ATLAN_MCP_URL: "https://redhat.atlan.com/mcp/api-key"
  PLOT_ENABLED: "true"
  PLOT_MAX_ROWS: "5000"
  MPLCONFIGDIR: "/tmp/matplotlib"
  AGENT_PUBLIC_BASE_URL: "..."
  LANGFUSE_TRACING_ENVIRONMENT: "production"
  AUTH_ENABLED: "true"
  AUTH_AUDIENCE: "account"
  AUTH_ISSUER: "https://auth.stage.redhat.com/auth/realms/EmployeeIDP"
  AUTH_JWKS_URL: "https://auth.stage.redhat.com/auth/realms/EmployeeIDP/protocol/openid-connect/certs"
  AUTH_ALGORITHMS: "RS256"
  AUTH_VERIFY_EXP: "true"
  AUTH_VERIFY_AUD: "true"